import Head from 'next/head'
import Navbar from '../components/Navbar/navbar'
import Banner from '../components/Banner/banner'
export default function Home() {
  return (
    <div>
      <Head>
        <title>لایت | دنیایی برنامه نویسی</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar/>
      <Banner/>
    </div>
  )
}
